/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author salsabilamaa
 */
public class Frame_MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Frame_MenuAdmin
     */
    public Frame_MenuAdmin() {
        initComponents();
    }

    public void setTxtUmum(String nilai){
        outUmum.setText(nilai);
    }
    
    public void setTxtIPA(String nilai){
        outIPA.setText(nilai);
    }
    
    public void setTxtIPS(String nilai){
        outIPS.setText(nilai);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Output_NilaiStandar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        outUmum = new javax.swing.JLabel();
        outIPA = new javax.swing.JLabel();
        outIPS = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInputNilai = new javax.swing.JButton();
        btnDaftarCalonSiswa = new javax.swing.JButton();
        btnPengumuman = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnDaftarRegistrasi = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Nilai Standar");

        jLabel7.setText("Umum           :");

        jLabel8.setText("IPA               :");

        jLabel9.setText("IPS               :");

        btnUpdate.setText("Update Nilai");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(outUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(outIPA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addGap(19, 19, 19)
                        .addComponent(outIPS, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnUpdate)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(outUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(outIPA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(outIPS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(btnUpdate)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Output_NilaiStandarLayout = new javax.swing.GroupLayout(Output_NilaiStandar.getContentPane());
        Output_NilaiStandar.getContentPane().setLayout(Output_NilaiStandarLayout);
        Output_NilaiStandarLayout.setHorizontalGroup(
            Output_NilaiStandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(Output_NilaiStandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Output_NilaiStandarLayout.setVerticalGroup(
            Output_NilaiStandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(Output_NilaiStandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu Admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 28, -1, -1));

        btnInputNilai.setText("Input Nilai Standar");
        btnInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputNilaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnInputNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 370, 32));

        btnDaftarCalonSiswa.setText("Daftar Calon Siswa");
        btnDaftarCalonSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarCalonSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarCalonSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 370, 32));

        btnPengumuman.setText("Pengumuman");
        btnPengumuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengumumanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPengumuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 370, 32));

        btnLogOut.setText("Keluar");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 20));

        btnDaftarRegistrasi.setText("Daftar Registrasi");
        btnDaftarRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarRegistrasiActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputNilaiActionPerformed
        Frame_NilaiStandar nilai = new Frame_NilaiStandar();
        nilai.setVisible(true);
        nilai.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnInputNilaiActionPerformed

    private void btnDaftarCalonSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarCalonSiswaActionPerformed
        Frame_DaftarCalonSiswa list = new Frame_DaftarCalonSiswa();
        list.setVisible(true);
        list.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnDaftarCalonSiswaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Frame_UpdateNilaiStandar update = new Frame_UpdateNilaiStandar();
        update.setVisible(true);
        update.setLocationRelativeTo(null);
        Output_NilaiStandar.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPengumumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengumumanActionPerformed
        Frame_Pengumuman pengumuman = new Frame_Pengumuman();
        pengumuman.setVisible(true);
        pengumuman.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnPengumumanActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Frame_Login login = new Frame_Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDaftarRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarRegistrasiActionPerformed
        Frame_DaftarRegistrasi list = new Frame_DaftarRegistrasi();
        list.setVisible(true);
        list.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnDaftarRegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Output_NilaiStandar;
    private javax.swing.JButton btnDaftarCalonSiswa;
    private javax.swing.JButton btnDaftarRegistrasi;
    private javax.swing.JButton btnInputNilai;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPengumuman;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel outIPA;
    private javax.swing.JLabel outIPS;
    private javax.swing.JLabel outUmum;
    // End of variables declaration//GEN-END:variables
}
